import React from 'react';
import TextField from '@material-ui/core/TextField';
import Autocomplete from '@material-ui/lab/Autocomplete';

export default function LocationBox(props) {

  function handleLocationChange(event,value) {
    // Here, we invoke the callback with the new value
    props.onChange(value);
}

  return (
    <Autocomplete
      id="location-box"
      options={locations}
      getOptionLabel={(option) => option.location}
      groupBy={(option=>option.type)}
      style={{ position:'relative', top:'10%', left: '40%', width: 300 }}
      renderInput={(params) => <TextField {...params} label="Select Country/State" variant="outlined" />}
      onChange={handleLocationChange}
    />
  );
}

const locations = [
    {location:'Bangladesh', type:'Country'},
    {location:'Malaysia', type:'Country'},
    {location:'Yemen', type:'Country'},
    {location:'Christmas Island', type:'Country'},
    {location:'Lesotho', type:'Country'},
    {location:'Ecuador', type:'Country'},
    {location:'Mauritius', type:'Country'},
    {location:'Peru', type:'Country'},
    {location:'South America', type:'Country'},
    {location:"Côte D'Ivoire", type:'Country'},
    {location:"Tunisia", type:'Country'},
    {location:"Anguilla", type:'Country'},
    {location:"Spain", type:'Country'},
    {location:'Slovenia', type:'Country'},
    {location:"Senegal", type:'Country'},
    {location:'Austria',type:'Country'},
    {location:'Kingman Reef',type:'Country'},
    {location:'Gaza Strip',type:'Country'},
    {location:'Turks And Caicas Islands',type:'Country'},
    {location:'North Korea',type:'Country'},
    {location:'New Caledonia',type:'Country'},
    {location:'Somalia',type:'Country'},
    {location:'British Virgin Islands',type:'Country'},
    {location:'Seychelles',type:'Country'},
    {location:'Libya',type:'Country'},
    {location:'Israel',type:'Country'},
    {location:'Europe',type:'Country'},
    {location:'Andorra',type:'Country'},
    {location:'Jordan',type:'Country'},
    {location:'Sint Maarten',type:'Country'},
    {location:'Ukraine',type:'Country'},
    {location:'Uruguay',type:'Country'},
    {location:'Svalbard And Jan Mayen',type:'Country'},
    {location:'Netherlands (Europe)',type:'Country'},
    {location:'Saudi Arabia',type:'Country'},
    {location:'Kenya',type:'Country'},
    {location:'Sierra Leone',type:'Country'},
    {location:'Bhutan',type:'Country'},
    {location:'Serbia',type:'Country'},
    {location:'Djibouti',type:'Country'},
    {location:'Egypt',type:'Country'},
    {location:'Nicaragua'},
    {location:'Aruba',type:'Country'},
    {location:'Paraguay',type:'Country'},
    {location:'Iran',type:'Country'},
    {location:'French Polynesia',type:'Country'},
    {location:'Denmark',type:'Country'},
    {location:'Iraq',type:'Country'},
    {location:'Romania',type:'Country'},
    {location:'Guinea Bissau',type:'Country'},
    {location:'Guatemala',type:'Country'},
    {location:'El Salvador',type:'Country'},
    {location:'Eritrea',type:'Country'},
    {location:'Cameroon',type:'Country'},
    {location:'Comoros',type:'Country'},
    {location:'Guadeloupe',type:'Country'},
    {location:'Liberia',type:'Country'},
    {location:'Cyprus',type:'Country'},
    {location:"Hong Kong",type:'Country'},
    {location:'Morocco',type:'Country'},
    {location:'Mongolia',type:'Country'},
    {location:'Portugal',type:'Country'},
    {location:'Curaçao',type:'Country'},
    {location:'Swaziland',type:'Country'},
    {location:'Lebanon',type:'Country'},
    {location:'Bahamas',type:'Country'},
    {location:'United States',type:'Country'},
    {location:'Madagascar',type:'Country'},
    {location:'San Marino',type:'Country'},
    {location:'Guyana',type:'Country'},
    {location:'Bahrain',type:'Country'},
    {location:'Denmark (Europe)',type:'Country'},
    {location:'Saint Martin',type:'Country'},
    {location:'Mali',type:'Country'},
    {location:'Togo',type:'Country'},
    {location:'Sri Lanka',type:'Country'},
    {location:'Timor Leste',type:'Country'},
    {location:'Bolivia',type:'Country'},
    {location:'Canada',type:'Country'},
    {location:'Antigua And Barbuda',type:'Country'},
    {location:'Vietnam',type:'Country'},
    {location:'Niger',type:'Country'},
    {location:'Bonaire, Saint Eustatius And Saba',type:'Country'},
    {location:'Macedonia',type:'Country'},
    {location:'Tanzania',type:'Country'},
    {location:'Oceania',type:'Country'},
    {location:'Croatia',type:'Country'},
    {location:'Liechtenstein',type:'Country'},
    {location:'Africa',type:'Country'},
    {location:'Moldova',type:'Country'},
    {location:'Equatorial Guinea',type:'Country'},
    {location:'Brazil',type:'Country'},
    {location:'Martinique',type:'Country'},
    {location:'Sudan',type:'Country'},
    {location:'Georgia',type:'Country'},
    {location:'Mauritania',type:'Country'},
    {location:'Congo (Democratic Republic Of The)',type:'Country'},
    {location:'Philippines',type:'Country'},
    {location:'Ghana',type:'Country'},
    {location:'Åland',type:'Country'},
    {location:'Colombia',type:'Country'},
    {location:'Turkmenistan',type:'Country'},
    {location:'Ireland',type:'Country'},
    {location:'Asia',type:'Country'},
    {location:'Belgium',type:'Country'},
    {location:'Samoa',type:'Country'},
    {location:'Iceland',type:'Country'},
    {location:'Sweden',type:'Country'},
    {location:'Zambia',type:'Country'},
    {location:'Guam',type:'Country'},
    {location:'Dominican Republic',type:'Country'},
    {location:'United Kingdom',type:'Country'},
    {location:'Norway',type:'Country'},
    {location:'United Kingdom (Europe)',type:'Country'},
    {location:'Chile',type:'Country'},
    {location:'Burkina Faso',type:'Country'},
    {location:'Palau',type:'Country'},
    {location:'Burma',type:'Country'},
    {location:'Sao Tome And Principe',type:'Country'},
    {location:'American Samoa',type:'Country'},
    {location:'China',type:'Country'},
    {location:'Kyrgyzstan',type:'Country'},
    {location:'Malta',type:'Country'},
    {location:'Greece',type:'Country'},
    {location:'Saint Vincent And The Grenadines',type:'Country'},
    {location:'Reunion',type:'Country'},
    {location:'Saint Barthélemy',type:'Country'},
    {location:'Costa Rica',type:'Country'},
    {location:'Russia',type:'Country'},
    {location:'Switzerland',type:'Country'},
    {location:'Puerto Rico',type:'Country'},
    {location:'Bulgaria',type:'Country'},
    {location:'South Africa',type:'Country'},
    {location:'Fiji',type:'Country'},
    {location:'Syria',type:'Country'},
    {location:'Uzbekistan',type:'Country'},
    {location:'Venezuela',type:'Country'},
    {location:'Armenia',type:'Country'},
    {location:'Jersey',type:'Country'},
    {location:'Greenland',type:'Country'},
    {location:'Isle Of Man',type:'Country'},
    {location:'Falkland Islands (Islas Malvinas)',type:'Country'},
    {location:'Barbados',type:'Country'},
    {location:'Kazakhstan',type:'Country'},
    {location:'Papua New Guinea',type:'Country'},
    {location:'Gambia',type:'Country'},
    {location:'Cayman Islands',type:'Country'},
    {location:'Palestina',type:'Country'},
    {location:'Baker Island',type:'Country'},
    {location:'South Georgia And The South Sandwich Isla',type:'Country'},
    {location:'Guernsey',type:'Country'},
    {location:'India',type:'Country'},
    {location:'Bosnia And Herzegovina',type:'Country'},
    {location:'Cape Verde',type:'Country'},
    {location:'Thailand',type:'Country'},
    {location:'Haiti',type:'Country'},
    {location:'Estonia',type:'Country'},
    {location:'Kuwait',type:'Country'},
    {location:'Namibia',type:'Country'},
    {location:'Northern Mariana Islands',type:'Country'},
    {location:'Czech Republic',type:'Country'},
    {location:'Faroe Islands',type:'Country'},
    {location:'Palmyra Atoll',type:'Country'},
    {location:'Heard Island And Mcdonald Islands',type:'Country'},
    {location:'French Guiana',type:'Country'},
    {location:'Dominica',type:'Country'},
    {location:'Nepal',type:'Country'},
    {location:'Taiwan',type:'Country'},
    {location:'Algeria',type:'Country'},
    {location:'Uganda',type:'Country'},
    {location:'Laos',type:'Country'},
    {location:'France',type:'Country'},
    {location:'Trinidad And Tobago',type:'Country'},
    {location:'Botswana',type:'Country'},
    {location:'Finland',type:'Country'},
    {location:'Honduras',type:'Country'},
    {location:'Monaco',type:'Country'},
    {location:'Guinea',type:'Country'},
    {location:'France (Europe)',type:'Country'},
    {location:'Tajikistan',type:'Country'},
    {location:'Turkey',type:'Country'},
    {location:'Angola',type:'Country'},
    {location:'Niue',type:'Country'},
    {location:'Suriname',type:'Country'},
    {location:'Cuba',type:'Country'},
    {location:'Jamaica',type:'Country'},
    {location:'Montserrat',type:'Country'},
    {location:'Indonesia',type:'Country'},
    {location:'Netherlands',type:'Country'},
    {location:'Mayotte',type:'Country'},
    {location:"Lithuania",type:'Country'},
    {location:'Luxembourg',type:'Country'},
    {location:'Saint Kitts And Nevis',type:'Country'},
    {location:'Mexico',type:'Country'},
    {location:'Benin',type:'Country'},
    {location:'Burundi',type:'Country'},
    {location:'Germany',type:'Country'},
    {location:'South Korea',type:'Country'},
    {location:'Virgin Islands',type:'Country'},
    {location:'Federated States Of Micronesia',type:'Country'},
    {location:'French Southern And Antarctic Lands',type:'Country'},
    {location:'Pakistan',type:'Country'},
    {location:'Congo',type:'Country'},
    {location:'Azerbaijan',type:'Country'},
    {location:'Central African Republic',type:'Country'},
    {location:'United Arab Emirates',type:'Country'},
    {location:'Chad',type:'Country'},
    {location:'Saint Lucia',type:'Country'},
    {location:'Latvia',type:'Country'},
    {location:'Western Sahara',type:'Country'},
    {location:'Grenada',type:'Country'},
    {location:'Qatar',type:'Country'},
    {location:'Poland',type:'Country'},
    {location:'Kiribati',type:'Country'},
    {location:'Rwanda',type:'Country'},
    {location:'Tonga',type:'Country'},
    {location:'New Zealand',type:'Country'},
    {location:'Solomon Islands',type:'Country'},
    {location:'Japan',type:'Country'},
    {location:'Belize',type:'Country'},
    {location:'Montenegro',type:'Country'},
    {location:'Slovakia',type:'Country'},
    {location:'Mozambique',type:'Country'},
    {location:'Albania',type:'Country'},
    {location:'North America',type:'Country'},
    {location:'Afghanistan',type:'Country'},
    {location:'Zimbabwe',type:'Country'},
    {location:'Belarus',type:'Country'},
    {location:'Saint Pierre And Miquelon',type:'Country'},
    {location:'Macau',type:'Country'},
    {location:'Argentina',type:'Country'},
    {location:'Nigeria',type:'Country'},
    {location:'Ethiopia',type:'Country'},
    {location:'Gabon',type:'Country'},
    {location:'Australia',type:'Country'},
    {location:'Malawi',type:'Country'},
    {location:'Panama',type:'Country'},
    {location:'Italy',type:'Country'},
    {location:'Hungary',type:'Country'},
    {location:'Singapore',type:'Country'},
    {location:'Cambodia',type:'Country'},
    {location:'Oman',type:'Country'},
    {location:'Indiana',type:'State'},
    {location:'Florida',type:'State'},
    {location:'Delaware',type:'State'},
    {location:'Rhode Island',type:'State'},
    {location:'Connecticut',type:'State'},
    {location:'Pennsylvania',type:'State'},
    {location:'Oklahoma',type:'State'},
    {location:'New York',type:'State'},
    {location:'Ohio',type:'State'},
    {location:'New Jersey',type:'State'},
    {location:'Nevada',type:'State'},
    {location:'Wyoming',type:'State'},
    {location:'Nebraska',type:'State'},
    {location:'West Virginia',type:'State'},
    {location:'North Dakota',type:'State'},
    {location:'Kansas',type:'State'},
    {location:'South Carolina',type:'State'},
    {location:'North Carolina',type:'State'},
    {location:'Georgia',type:'State'},
    {location:'Alabama',type:'State'},
    {location:'Arizona',type:'State'},
    {location:'Virginia',type:'State'},
    {location:'Maine',type:'State'},
    {location:'New Hampshire',type:'State'},
    {location:'Illinois',type:'State'},
    {location:'Montana',type:'State'},
    {location:'Massachusetts',type:'State'},
    {location:'South Dakota',type:'State'},
    {location:'Mississippi',type:'State'},
    {location:'Missouri',type:'State'},
    {location:'New Mexico',type:'State'},
    {location:'California',type:'State'},
    {location:'Michigan',type:'State'},
    {location:'Wisconsin',type:'State'},
    {location:'Vermont',type:'State'},
    {location:'Oregon',type:'State'},
    {location:'Louisiana',type:'State'},
    {location:'Washington',type:'State'},
    {location:'Idaho',type:'State'},
    {location:'Utah',type:'State'},
    {location:'Colorado',type:'State'},
    {location:'Minnesota',type:'State'},
    {location:'Texas',type:'State'},
    {location:'Arkansas',type:'State'},
    {location:'Kentucky',type:'State'},
    {location:'Maryland',type:'State'},
    {location:'Tennessee',type:'State'},
    {location:'Iowa',type:'State'}
];

